sudo: false
notifications:
  email: false
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - wget https://codecov.io/bash -O $HOME/codecov; chmod +x $HOME/codecov
before_script:
  - coverage=OFF
  - if [ "$CXX" = "g++" ]; then
        export CXX="g++-4.8" CC="gcc-4.8";
        coverage=ON;
    fi
  - mkdir ./build
  - cd ./build
script:
  - cmake cmake -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ..
  - make -j5
  - cd ./bin/
  - ./test_ml-lib
 # Push coverage info on codecov.io
  - gcov /home/travis/build/DolotovEvgeniy/ml-lib
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: dolotov.evgeniy@gmail.com
